### ISSUE TITLE
Fix error in line 145 of normalize.py

### ISSUE THREAD

**Issue by ybracke** [aehrm/hybrid_textnorm#1]
There is an error in line [145 of normalize.py](https://github.com/aehrm/hybrid_textnorm/blob/f37c123e8797dc192c00a9216d2955329b5f808f/normalize.py#L145) that causes an `AttributeError` if `args.output_text` is None.

Solution: Change line 145 to `print(' '.join(tokens), file=output_file)`

**Comment by aehrm** [comment]
Thanks, fixed in above commit.
